name:                local-xmobar
version:             0.1.0.0
github:              "Disco-Dave/dotfiles"
license:             BSD3
author:              "David Burkett"
maintainer:          "david@davidburkett.xyz"
copyright:           "2020 David Burkett"

dependencies:
- base >= 4.7 && < 5
- xmobar

executables:
  xmobar-primary:
    main: xmobar-primary.hs
