# Set caps lock key to be escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# Start the compositor so we can have transparency and shadow effects
picom &

# Run commands only necessary for my desktop
if grep -q compe /etc/hostname; then
    # Set the correct resolution and orientation for my two monitors
    xrandr --output DVI-I-0 \
        --off --output DVI-I-1 \
        --off --output HDMI-0 --off \
        --output DP-0 --off \
        --output DP-1 --off \
        --output DP-2 --mode 3840x2160 --pos 0x0 --rotate normal --primary \
        --output DP-3 --off \
        --output DP-4 --mode 3840x2160 --pos 3840x0 --rotate normal \
        --output DP-5 --off

    # Load Xresources file
    # https://wiki.archlinux.org/index.php/X_resources#xinitrc
    xresources="$HOME/.config/X11/compe_Xresources"
    [[ -f $xresources ]] && xrdb -merge -I$HOME $xresources

    xsetroot -xcf /usr/share/icons/Vanilla-DMZ/cursors/left_ptr 32
else
    xsetroot -cursor_name left_ptr
fi

# Draw the wallpaper
feh --no-fehbg --bg-center --no-xinerama ~/.config/dotfiles/assets/wallpaper.jpg &

# Generate alacritty config
gen-alacritty &

# Set custom ELECOM Huge settings
$HOME/.config/dotfiles/scripts/set_elecom_huge_settings

# Start our window manager XMonad. XMonad will then start other applications
# for us ie: xmobar, notifcation daemon, redshift, nm-applet, etc.
exec xmonad

# vim: filetype=sh:
