#!/usr/bin/env bash

# Set caps lock key to be escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# Start the compositor so we can have transparency and shadow effects
picom &

# Fix screen stuff
xsetroot -cursor_name left_ptr
~/.config/xrandr/set.sh

# Draw the wallpaper
feh --no-fehbg --bg-center --no-xinerama ~/.config/dotfiles/assets/wallpaper.jpg &

# Generate alacritty config
(cd ~/.config/alacritty && ./merge.sh) &

# Set custom ELECOM Huge settings
~/.config/dotfiles/scripts/set_elecom_huge_settings &

# Load nvidia settings
[[ -f /usr/bin/nvidia-settings ]] && nvidia-settings --load-config-only --config=~/.config/nvidia-settings-rc

# Start our window manager XMonad. XMonad will then start other applications
# for us ie: xmobar, notifcation daemon, redshift, nm-applet, etc.
exec ~/.cache/xmonad/xmonad-x86_64-linux

# vim: filetype=sh:
