#!/bin/bash

xresources="$XDG_CONFIG_HOME/X11/Xresources"
cached_xmonad="$XDG_CACHE_HOME/xmonad/xmonad-x86_64-linux"
xrandr_script="$XDG_CONFIG_HOME/X11/xrandr.sh"

if [ -x "$xrandr_script" ]; then
	"$xrandr_script"
fi

xsetroot -cursor_name left_ptr
xsetroot -xcf /usr/share/icons/Vanilla-DMZ/cursors/left_ptr 16

if [ -f "$xresources" ]; then
	xrdb -merge -I"$HOME" "$xresources"
fi

if [ -x "$cached_xmonad" ]; then
	# exec dbus-launch --exit-with-session "$cached_xmonad"
	exec "$cached_xmonad"
else
	# exec dbus-launch --exit-with-session xmonad
	exec monad
fi
