#!/bin/bash

set -e

TEMP_DIR="$(mktemp -d /tmp/xmonad-build-XXXXXXXXXX)"
trap 'rm -r $TEMP_DIR' exit

cd "$XDG_CONFIG_HOME/xmonad/xmonad"

cabal install \
  -O2 \
  --installdir "$TEMP_DIR" \
  --install-method copy \
  xmonad-local:exe:xmonad

mv "$TEMP_DIR/xmonad" "$1"
