#!/usr/bin/env bash

set -e

TEMP_DIR="$(mktemp -d)"
trap 'rm -r $TEMP_DIR' exit

cd "$XDG_CONFIG_HOME/xmonad"

cabal build exe:xmonad
cp "$(cabal list-bin exe:xmonad)" "$TEMP_DIR/xmonad"
mv "$TEMP_DIR/xmonad" "$1"
