#!/bin/bash

# Set caps lock key to be escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# Setup monitors
bash ~/.screenlayout/desktop.sh

# Start the compositor
compton &

# Set the wallpaper
feh --no-fehbg --bg-center ~/Pictures/caribou.jpg

# Fix monitors
autorandr

# Fix DPI
xrdb -merge -I$HOME ~/.config/X11/Xresources

# Set default cursor
xsetroot -cursor_name left_ptr


# Start xmonad
exec zsh -c "$HOME/.cache/xmonad/xmonad-x86_64-linux"

# vim: filetype=sh:
