#!/bin/bash

set -e

# TODO: Look into https://wiki.archlinux.org/index.php/Convert_FLAC_to_MP3#Parallel_with_recursion

for folder in "$@"; do
    new_folder="$HOME"/music/"$(basename "$folder")"
    rsync -av "$folder"/ "$new_folder"/ --exclude="*.flac"
    parallel ffmpeg -i {} -qscale:a 0 "'$new_folder'"/{/.}.mp3 ::: "$folder"/*.flac   
done
