#!/bin/bash

set -e

for FOLDER in "$@"; do
    NEW_FOLDER="$HOME/music/$(basename "$FOLDER")"

    rsync -av "$FOLDER"/ "$NEW_FOLDER"/ --exclude="**/*.flac"

    fd --search-path "$FOLDER" -t f -e flac -x ffmpeg -i "{}" -qscale:a 0 "$NEW_FOLDER/{/.}.mp3"
done
