# Ensure xterm uses 256 colors if used
export TERM=xterm-256color

# XDG Directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Set default editor to neovim
export EDITOR="nvim"
export VISUAL="nvim"

# Set default web browser to firefox if I have a graphic display
# or lynx if I do not.
if [ -n "$DISPLAY" ]; then
    export BROWSER="firefox"
else 
    export BROWSER="lynx"
fi

export XAUTHORITY="$XDG_DATA_HOME/Xauthority"
export XMONAD_CONFIG_HOME="$XDG_CONFIG_HOME"/xmonad
export XMONAD_DATA_HOME="$XDG_DATA_HOME"/xmonad
export XMONAD_CACHE_HOME="$XDG_CACHE_HOME"/xmonad

export NUGET_PACKAGES="$XDG_CACHE_HOME"/nuget
export STACK_ROOT="$XDG_DATA_HOME"/stack
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc

export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export LESSHISTFILE=-

# Global path
typeset -U PATH path
path=(
    "$HOME/.local/bin" 
    "$XDG_DATA_HOME/cargo/bin"
    "$HOME/.local/share/npm/bin"
    "$HOME/.local/bin"
    "$path[@]")
export PATH

# vim: set nowrap:
