# Ensure xterm uses 256 colors if used
export TERM=alacritty

# Set XDG Base Directories variables since these aren't automatically
# set for us. However $XDG_RUNTIME_DIR is.
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"

# Set default editor to neovim
export EDITOR="nvim"
export VISUAL="nvim"

# Set default web browser to firefox if I have a graphic display
# or lynx if I do not.
if [ -n "$DISPLAY" ]; then
    export BROWSER="firefox"
else 
    export BROWSER="lynx"
fi

# Use GTK2 theme with QT
export QT_QPA_PLATFORMTHEME=gtk2

# Enable hardware acceleration for Firefox https://wiki.archlinux.org/index.php/Firefox#Hardware_video_acceleration
export MOZ_X11_EGL=1 

# Prevent an assortment of programs from dumping files into the
# home directory and instead force them to use XDG Base Directories.
# https://wiki.archlinux.org/index.php/XDG_Base_Directory#Support
export CABAL_DIR="$XDG_DATA_HOME"/cabal
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CARGO_TARGET_DIR="$XDG_CACHE_HOME"/cargo
export GHCUP_USE_XDG_DIRS="yes"
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/nuget
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export STACK_ROOT="$XDG_DATA_HOME"/stack
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat
export XAUTHORITY="$XDG_DATA_HOME/Xauthority"
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XMONAD_CACHE_HOME="$XDG_CACHE_HOME"/xmonad
export XMONAD_CONFIG_HOME="$XDG_CONFIG_HOME"/xmonad
export XMONAD_DATA_HOME="$XDG_DATA_HOME"/xmonad
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc

export LESSHISTFILE=-

# Set our global path variable.
# https://wiki.archlinux.org/index.php/Zsh#Configuring_$PATH
typeset -U PATH path
path=(
    "$HOME/.local/bin" 
    "$HOME/.local/share/ghcup/env"
    "$XDG_DATA_HOME/cabal/bin"
    "$XDG_DATA_HOME/cargo/bin"
    "$HOME/.local/share/npm/bin"
    "$path[@]")
export PATH
