# Official ZSH documentation: http://zsh.sourceforge.net/Doc/Release/index.html#Top
# Arch Wiki article: https://wiki.archlinux.org/index.php/Zsh

fpath=(~/.local/share/zsh/functions/ $fpath)

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
export GIT_PROMPT_EXECUTABLE="haskell"
source $HOME/.local/share/zsh/plugins/zsh-git-prompt/zshrc.sh


# Enable substring searches for up and down arrows
# https://github.com/zsh-users/zsh-history-substring-search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down


# Use vim key bindings
# https://wiki.archlinux.org/index.php/Zsh#Key_bindings
bindkey -v


# Enable auto completion
# https://wiki.archlinux.org/index.php/Zsh#Command_completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION


# Setup history
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export HISTSIZE=99999999
export SAVEHIST=99999999


# Setup custom prompt
# https://wiki.archlinux.org/index.php/Zsh#Customized_prompt
# http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
PS1='%B%F{white}%n@%M%f:%F{blue}%/%f%b $(git_super_status)
%(!.#.$) '
RPS1="[%*]"


# Add additional colors to various commands
# https://wiki.archlinux.org/index.php/Color_output_in_console#diff
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}
